'use client'

import { useState } from 'react'
import type { ReactNode } from 'react'
import Icon from '@/components/ui/Icon'
import type { SessionUser } from '@/lib/types'

/**
 * Creator-facing Tutorial tab.
 *
 * Walkthrough = sectioned step cards, each with a REAL screenshot of the live
 * tool (captured headless, personal data swapped for placeholders, earnings
 * normalized, a few rows seeded with clean example values). Numbered callout
 * pins sit in whitespace over each shot and line up with a legend below it.
 * Q&A = classic expand/fold accordion.
 *
 * Copy rule: NO em dashes, en dashes, or dash separators in visible text.
 *
 * Screenshots live in /public/assets/tutorial and are regenerated by the
 * headless capture script when the UI changes meaningfully.
 */

export default function TutorialTab({ session: _session }: { session: SessionUser }) {
  const [view, setView] = useState<'walkthrough' | 'qa'>('walkthrough')
  return (
    <div className="main">
      <div className="page-head" style={{ alignItems: 'flex-end' }}>
        <div className="page-title">How this tool works</div>
        <div className="tut-seg" role="tablist" aria-label="Tutorial views">
          <button role="tab" aria-selected={view === 'walkthrough'} className={`tut-seg-btn${view === 'walkthrough' ? ' active' : ''}`} onClick={() => setView('walkthrough')}>Walkthrough</button>
          <button role="tab" aria-selected={view === 'qa'} className={`tut-seg-btn${view === 'qa' ? ' active' : ''}`} onClick={() => setView('qa')}>Q&amp;A</button>
        </div>
      </div>
      <div className="tut-scroll">
        <div className="tut-doc">{view === 'walkthrough' ? <Walkthrough /> : <QA />}</div>
      </div>
    </div>
  )
}

/* ---- primitives ---- */

type PinSpec = { n: number; x: number; y: number }

/** A real screenshot in a clean frame, with numbered pins floated in
 *  whitespace at percentage coordinates so they never cover content. */
function Shot({ src, w, h, alt, pins, max }: { src: string; w: number; h: number; alt: string; pins?: PinSpec[]; max?: number }) {
  return (
    <div className="tut-shot" style={max ? { maxWidth: max } : undefined}>
      {/* eslint-disable-next-line @next/next/no-img-element */}
      <img src={src} width={w} height={h} alt={alt} loading="lazy" />
      {pins?.map((p) => (
        <span key={p.n} className="tut-pin tut-pin-abs" style={{ left: `${p.x}%`, top: `${p.y}%` }}>{p.n}</span>
      ))}
    </div>
  )
}

function Legend({ items }: { items: ReactNode[] }) {
  return (
    <ol className="tut-legend">
      {items.map((it, i) => (
        <li key={i}><span className="tut-legend-num">{i + 1}</span><span>{it}</span></li>
      ))}
    </ol>
  )
}

function StepCard({ n, title, lead, children, legend }: { n: number; title: string; lead?: ReactNode; children?: ReactNode; legend?: ReactNode[] }) {
  return (
    <section className="tut-step">
      <div className="tut-step-head">
        <span className="tut-step-num">{n}</span>
        <h3 className="tut-step-title">{title}</h3>
      </div>
      {lead && <p className="tut-step-lead">{lead}</p>}
      {children}
      {legend && <Legend items={legend} />}
    </section>
  )
}

function SectionTitle({ children }: { children: ReactNode }) {
  return <h2 className="tut-section-title">{children}</h2>
}

/* ---- walkthrough ---- */

function Walkthrough() {
  return (
    <>
      <SectionTitle>Getting started</SectionTitle>

      <StepCard
        n={1}
        title="Log in"
        lead="Open the dashboard link we sent you and enter the email and password we gave you. You land on your profile, which is your whole world in this tool. You can only ever see your own videos and payments."
        legend={[
          <>Your email.</>,
          <>The password we sent you (watch for auto capitalization on phones).</>,
          <>Press <b>Sign in</b>.</>,
        ]}
      >
        <Shot src="/assets/tutorial/login.png" w={896} h={764} max={420} alt="The sign in screen"
          pins={[{ n: 1, x: 90, y: 49 }, { n: 2, x: 90, y: 70 }, { n: 3, x: 90, y: 88 }]} />
      </StepCard>

      <StepCard
        n={2}
        title="Read your profile at a glance"
        lead="The top of your page shows your linked accounts and three summary cards."
        legend={[
          <>Your linked handles on each platform. Click a handle to open that profile. If one is wrong or you renamed it, tell us (see section 8).</>,
          <><b>Current period</b>: what you have earned so far this period. It keeps moving until the period is paid.</>,
          <><b>All time earned</b>: the total from periods that have already been paid out.</>,
          <><b>PayPal</b>: where we send your money. Click it to open PayPal. If it is wrong, message your payments manager right away.</>,
        ]}
      >
        <Shot src="/assets/tutorial/profile.png" w={1976} h={388} alt="Your linked accounts and summary cards"
          pins={[{ n: 1, x: 4, y: 8 }, { n: 2, x: 2.5, y: 38 }, { n: 3, x: 34.5, y: 38 }, { n: 4, x: 67, y: 38 }]} />
      </StepCard>

      <SectionTitle>Your videos and payout</SectionTitle>

      <StepCard
        n={3}
        title="Find your videos"
        lead="Videos this cycle lists every video for the period you are viewing. If you posted the same video on more than one platform, it shows as a single row, not several."
        legend={[
          <>One row is one video, even when you posted it across several platforms.</>,
          <>Views on each platform. Tap a number to open the post.</>,
          <><b>Highest views</b> is the single platform with the most views. That is the number you are paid on.</>,
          <><b>Payout</b> is what that video earns at your tier.</>,
        ]}
      >
        <Shot src="/assets/tutorial/videos.png" w={1976} h={660} alt="The videos table"
          pins={[{ n: 1, x: 15, y: 24 }, { n: 2, x: 33, y: 24 }, { n: 3, x: 80, y: 10 }, { n: 4, x: 93, y: 10 }]} />
      </StepCard>

      <StepCard
        n={4}
        title="How your payout is calculated"
        lead="You are paid once per video, on the highest view count among the platforms you posted it on, never the sum. Videos under 1,000 views pay nothing. Views keep updating until the period is paid or the video turns 14 days old, whichever comes first. After that the number is locked."
      >
        <div className="tut-tiers">
          <table className="tut-tiers-tbl">
            <thead><tr><th>Highest views</th><th className="tut-r">Payout</th></tr></thead>
            <tbody>
              {[
                ['1,000 to 9,999', '$10'], ['10,000 to 49,999', '$30'], ['50,000 to 99,999', '$60'],
                ['100,000 to 249,999', '$120'], ['250,000 to 499,999', '$250'], ['500,000 to 999,999', '$400'],
                ['1M to 1.99M', '$600'], ['2M to 2.99M', '$800'], ['3M to 3.99M', '$1,000'],
                ['4M to 4.99M', '$1,250'], ['5M to 5.99M', '$1,600'], ['6M and above', '$1,600 plus $200 per extra million (max $2,400)'],
              ].map(([r, p]) => (<tr key={r}><td className="tut-mono">{r}</td><td className="tut-mono tut-r">{p}</td></tr>))}
            </tbody>
          </table>
        </div>
      </StepCard>

      <StepCard
        n={5}
        title="The Payable checkbox"
        lead="Every row has a checkbox. Checked means it counts toward your payout. Everything starts checked, so you normally never touch it. If you check a row yourself, it turns yellow to show you confirmed it."
        legend={[
          <>Checked counts toward your payout. Unchecked does not.</>,
          <>A <b>yellow</b> row is one you confirmed yourself.</>,
        ]}
      >
        <Shot src="/assets/tutorial/checkbox.png" w={1976} h={348} alt="The payable checkbox and a confirmed yellow row"
          pins={[{ n: 1, x: 4.5, y: 40 }, { n: 2, x: 2.5, y: 73 }]} />
      </StepCard>

      <StepCard
        n={6}
        title="Link two rows that are the same video"
        lead="Sometimes the same video shows up as two separate rows (a different cover frame or caption threw it off). Each one has a Link Post button. Click it, pick the row it belongs with, and they merge into one so your payout uses the higher view count."
        legend={[
          <>The same video split into two rows.</>,
          <>Press <b>Link Post</b> and choose its match. They become one row.</>,
        ]}
      >
        <Shot src="/assets/tutorial/linkpost.png" w={1976} h={348} alt="Two rows for the same video, each with a Link Post button"
          pins={[{ n: 1, x: 55, y: 40 }, { n: 2, x: 13.5, y: 68 }]} />
      </StepCard>

      <SectionTitle>Pay periods</SectionTitle>

      <StepCard
        n={7}
        title="When a video counts"
        lead="Each month has two pay periods: the 1st to the 15th, and the 16th to the end of the month. A video lands in a period by the date it went live, in US Eastern Time. The cutoff is midnight Eastern. The banner at the top of your page tells you which period you are viewing."
      >
        <Shot src="/assets/tutorial/header.png" w={1976} h={172} alt="The pay period banner at the top of your page"
          pins={[{ n: 1, x: 74, y: 50 }]} />
        <div className="tut-axis">
          <div className="tut-axis-segs">
            <div className="tut-axis-seg"><span className="tut-axis-seg-name">1st to 15th</span><span className="tut-axis-seg-pay">paid around end of month</span></div>
            <div className="tut-axis-seg"><span className="tut-axis-seg-name">16th to end of month</span><span className="tut-axis-seg-pay">paid around the 15th next month</span></div>
          </div>
          <div className="tut-axis-track">
            <span className="tut-axis-dot start" />
            <span className="tut-axis-cut" />
            <span className="tut-axis-dot end" />
          </div>
          <div className="tut-axis-dates">
            <span className="start">1st</span>
            <span className="mid">16th · midnight ET</span>
            <span className="end">last day</span>
          </div>
        </div>
        <div className="tut-note">
          <Icon name="info" size={15} />
          <span>In a different time zone? A post you make late at night can roll into the next day in Eastern Time and count in the next period. One exception: if it is the same video you also posted on another platform <b>before</b> the cutoff, the two get grouped and counted together in the earlier period, as long as the two posts are <b>within one day</b> of each other.</span>
        </div>
      </StepCard>

      <SectionTitle>Referrals</SectionTitle>

      <StepCard
        n={8}
        title="Refer a creator and earn $75"
        lead="Under Referrals, search the creator you referred, pick them, and press the plus. You earn $75 once that creator has posted at least 12 videos on their biggest platform, counted over their whole time in the program. If they already qualify, the $75 is added right away. If not, the row shows their progress and re checks every day. Each creator can be referred only once, ever."
        legend={[
          <>Search the creator, pick them, then press the plus.</>,
          <><b>Awarded</b> means the $75 is already counted in this period's total, automatically. <b>Bonus pending</b> means it pays out in whichever period they reach 12 videos, and it is added to your total then. You never have to claim it.</>,
          <>Press the <b>✕</b> to remove a referral you added by mistake (only before it has been paid).</>,
        ]}
      >
        <Shot src="/assets/tutorial/referrals.png" w={1976} h={470} alt="The referrals picker and example rows"
          pins={[{ n: 1, x: 48.5, y: 32 }, { n: 2, x: 66, y: 61 }, { n: 3, x: 95.5, y: 79 }]} />
      </StepCard>

      <SectionTitle>Who to message</SectionTitle>
      <p className="tut-help-lead">Start with your <b>creator lead</b> for anything general or if you are not sure where to go. Otherwise:</p>
      <ul className="tut-help-list">
        <li><span className="tut-chip">Payments and PayPal</span> when you will be paid, an amount looks wrong, or changing your PayPal email, ask <b>your payments manager</b>.</li>
        <li><span className="tut-chip">Technical problems</span> something looks broken, or a video genuinely is not tracked after you checked the Q&amp;A, ask <b>your admin</b>.</li>
      </ul>
      <p className="tut-help-foot">When you reach out, include what you expected, what you see instead, and the video link if it is about a specific video. Screenshots help a lot.</p>
    </>
  )
}

/* ---- Q&A ---- */

type QAItem = { q: string; a: ReactNode }
const QA_GROUPS: { group: string; items: QAItem[] }[] = [
  {
    group: 'Payout',
    items: [
      { q: 'Why does my video show $0 even though it has views?', a: <>Most likely it is under <b>1,000 views</b>, which is the minimum to earn. Or its checkbox is unchecked. Check both.</> },
      { q: 'Why is my payout based on one platform when I posted on three?', a: <>You are paid per <b>video</b>, not per upload. We take the <b>highest</b> view count among the platforms. Posting everywhere is still smart, since it raises the chance one version pops.</> },
      { q: 'My total went down since yesterday. What happened?', a: <>Usually one of two things. Either the system merged two rows that were the same video, so it pays once instead of twice, or a video was removed or made private. If something looks truly off, send us the link.</> },
      { q: 'My video blew up after the period was paid. Do I get more?', a: <>No. Views lock when the period is paid, or when the video turns 14 days old. The number at lock time is what pays.</> },
      { q: 'It is June. Why does my page show May?', a: <>The page shows the <b>oldest period that has not been paid yet</b>. Once May is paid it flips to June on its own. Your June videos are tracked the whole time.</> },
      { q: 'What is "All time earned"? It seems low.', a: <>It counts only periods that have <b>actually been paid out</b>. The current period is not in there yet. That lives in the Current period card.</> },
      { q: 'When do I get paid?', a: <>The 1st to 15th period is paid around the end of that month. The 16th to end of month period is paid around the 15th of the next month. For anything about a payment or amount, ask <b>your payments manager</b>.</> },
      { q: 'How do I change my PayPal email?', a: <>Message <b>your payments manager</b>. You cannot change it yourself.</> },
    ],
  },
  {
    group: 'Videos',
    items: [
      { q: 'I posted an hour ago and it is not showing. Is something broken?', a: <>No. The tool updates about twice a day, so give it up to 12 hours. If it is still missing after a full day, send us the link.</> },
      { q: 'My video is still missing after a day.', a: <>Common reasons: it is <b>private</b>, it was <b>deleted</b>, it was posted on a handle we do not have on file, you <b>renamed your handle</b>, or a required hashtag is missing from the caption. Send us the link and we will check.</> },
      { q: 'My reel is public and the link works, but it never shows up here.', a: <>Instagram only lets our data service see reels that are on your <b>profile grid</b>. If you posted it with <b>Show on profile</b> turned off, so it lives only in the Reels tab, or you hid it later, the service cannot see it even though the link works. Open the reel, tap the three dots, and turn on <b>Show on profile</b>. It will appear on the next update.</> },
      { q: 'I did a collab with another creator. Who gets paid?', a: <>Only the <b>main poster</b>, the account that owns the post. Collab videos are paid once, never to both creators. If you were the collaborator and not the original poster, it will not show on your page, and that is expected.</> },
      { q: 'I renamed my TikTok, Instagram, or YouTube handle. Do I need to tell you?', a: <><b>Yes, right away.</b> If we do not update your handle, your new videos stop being tracked and will not be paid. This is the number one cause of videos disappearing.</> },
      { q: 'The posted date on my video looks earlier than I expected.', a: <>If you used Instagram <b>trial reels</b>, the date is set to when you <b>first posted it as a trial</b>, not when you released it to everyone. So it can look earlier and may land in an earlier period. If it still looks wrong after that, send the link and the real date.</> },
      { q: 'Some of my videos are missing on one platform.', a: <>Our views come from a service that follows each of your accounts by handle. If the handle on file is wrong, or that account is set to track only your most recent videos, some can be left out. Send us your handle for that platform and we will check the setup.</> },
      { q: 'Why is there no Facebook column?', a: <>Columns show only for platforms we have on file for you. If you post on Facebook and want it tracked, send us your Facebook handle.</> },
      { q: 'Two of my rows are the same video, or one row should be two.', a: <>Same video split into two rows: use <b>Link Post</b> (see the walkthrough). One row wrongly combining two different videos: tell us and we will fix it.</> },
      { q: 'I deleted a video. What happens?', a: <>It stops counting within a few days on its own. Do not delete videos mid period if you want them paid.</> },
      { q: 'I unchecked a video by mistake. Can I undo it?', a: <>Yes, just check it again. The row turns yellow to show you confirmed it.</> },
    ],
  },
  {
    group: 'Referrals',
    items: [
      { q: 'My referral says "Bonus pending." How long until I get my $75?', a: <>Until the creator you referred reaches <b>12 videos on their biggest platform</b>. The row shows their progress and checks every day. You do not need to do anything.</> },
      { q: 'It says the creator was "already referred by someone."', a: <>Each creator can be referred only once, ever, and someone claimed them first.</> },
      { q: 'My referral qualified in a different period than when I added it.', a: <>The $75 lands in the period that was running <b>when they qualified</b>. The row tells you which period it was awarded in.</> },
      { q: 'I removed a referral by accident. Can I re add it?', a: <>Yes, search them and add again, as long as nobody else has claimed them since.</> },
      { q: 'Do I get $75 per video they post, or recurring?', a: <>No. It is a <b>one time $75</b> per referred creator.</> },
    ],
  },
  {
    group: 'Login',
    items: [
      { q: 'I cannot log in.', a: <>Check the exact email and password we sent, and watch for auto capitalization on phones. Still stuck? Ask your creator lead for a reset.</> },
      { q: 'It says "Creator not linked. Ask an admin to link your account."', a: <>Your login exists but is not connected to your profile yet. Message your creator lead and it is a quick fix on our side.</> },
    ],
  },
]

function QA() {
  const [open, setOpen] = useState<string | null>(null)
  return (
    <>
      {QA_GROUPS.map((grp) => (
        <div key={grp.group} className="tut-qa-group">
          <SectionTitle>{grp.group}</SectionTitle>
          <div className="tut-faq">
            {grp.items.map((item) => {
              const id = `${grp.group}:${item.q}`
              const isOpen = open === id
              return (
                <div key={id} className={`tut-faq-item${isOpen ? ' open' : ''}`}>
                  <button className="tut-faq-q" aria-expanded={isOpen} onClick={() => setOpen(isOpen ? null : id)}>
                    <span>{item.q}</span>
                    <Icon name="chevron-down" size={15} className="tut-faq-chev" />
                  </button>
                  {isOpen && <div className="tut-faq-a">{item.a}</div>}
                </div>
              )
            })}
          </div>
        </div>
      ))}
    </>
  )
}
